STA 556 – Homework 1

Benjamin Owusu Acquah

In [2]:
import pandas as pd

students = pd.read_csv("../data/raw/students.csv")
enrollments = pd.read_csv("../data/raw/enrollments.csv")
courses = pd.read_csv("../data/raw/courses.csv")

Part 1 — Inspect the data

In [3]:
# STUDENTS TABLE SUMMARY

print("Shape:", students.shape)

print("\nColumns and dtypes:")
print(students.dtypes)

print("\nMissing values:")
print(students.isna().sum())

print("\nLikely key columns (unique values):")
print(students.nunique())

Shape: (30, 11)

Columns and dtypes:
student_id               str
first_name               str
last_name                str
program                  str
year                     str
age                  float64
active                   str
entry_term               str
gpa                  float64
credits_completed      int64
advisor                  str
dtype: object

Missing values:
student_id           0
first_name           0
last_name            0
program              0
year                 0
age                  2
active               0
entry_term           0
gpa                  3
credits_completed    0
advisor              1
dtype: int64

Likely key columns (unique values):
student_id           30
first_name           30
last_name            30
program               4
year                  4
age                   8
active                2
entry_term            6
gpa                  25
credits_completed    11
advisor               4
dtype: int64

In [4]:
# ENROLLMENTS TABLE SUMMARY

print("Shape:", enrollments.shape)

print("\nColumns and dtypes:")
print(enrollments.dtypes)

print("\nMissing values:")
print(enrollments.isna().sum())

print("\nLikely key columns (unique values):")
print(enrollments.nunique())

Shape: (59, 9)

Columns and dtypes:
enrollment_id         str
student_id            str
course_id             str
term                  str
status                str
midterm_score       int64
final_score       float64
project_score     float64
attendance_pct    float64
dtype: object

Missing values:
enrollment_id     0
student_id        0
course_id         0
term              0
status            0
midterm_score     0
final_score       5
project_score     3
attendance_pct    2
dtype: int64

Likely key columns (unique values):
enrollment_id     59
student_id        30
course_id          9
term               3
status             2
midterm_score     30
final_score       34
project_score     31
attendance_pct    49
dtype: int64

In [5]:
# COURSES TABLE SUMMARY

print("Shape:", courses.shape)

print("\nColumns and dtypes:")
print(courses.dtypes)

print("\nMissing values:")
print(courses.isna().sum())

print("\nLikely key columns (unique values):")
print(courses.nunique())

Shape: (8, 7)

Columns and dtypes:
course_id          str
department         str
course_number    int64
course_title       str
credits          int64
level              str
delivery           str
dtype: object

Missing values:
course_id        0
department       0
course_number    0
course_title     0
credits          0
level            0
delivery         0
dtype: int64

Likely key columns (unique values):
course_id        8
department       3
course_number    8
course_title     8
credits          2
level            2
delivery         3
dtype: int64

Based on uniqueness checks in each table, the likely key columns are:

Students table: student_id

Each student has one unique ID.

Enrollments table: enrollment_id

Each enrollment record is uniquely identified by its enrollment ID.

Courses table: course_id

Each course has one unique course ID.

Both the students and enrollments tables contain missing values in important fields such as age, GPA, final scores, project scores, and attendance percentages. These internal missing values reduce the completeness of demographic and performance analyses. More importantly, the enrollments table contains student_id = S9999, which does not appear in the students table, and course_id = C999, which does not appear in the courses table. These are foreign‑key mismatches that will produce incomplete rows during merging and indicate referential integrity problems in the raw data.

Part 2 — Filtering and Derived Variables

a

In [6]:
# students with GPA above 3.0 AND more than 45 completed credits
subset = students.loc[
    (students["gpa"] > 3.0) &
    (students["credits_completed"] > 45)
]
subset

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor
0,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,Dr. Moreno
3,S1004,Sofia,Johnson,Computer Science,2nd,20.0,Yes,Spring 2026,3.05,63,Dr. Kim
10,S1011,Isabella,Lopez,Statistics,2nd,18.0,Yes,Fall 2024,3.22,54,Dr. Reed
11,S1012,Elijah,Clark,Data Science,4th,26.0,Yes,Fall 2025,3.31,72,Dr. Reed
15,S1016,Leo,Moore,Data Science,2nd,25.0,Yes,Spring 2026,3.31,96,Dr. Moreno
19,S1020,Daniel,Young,Mathematics,1st,22.0,Yes,Fall 2023,3.75,108,Dr. Shah
24,S1025,Chloe,Baker,Data Science,4th,19.0,Yes,Spring 2024,3.85,84,Dr. Moreno
27,S1028,Caleb,Hill,Mathematics,1st,20.0,No,Spring 2026,3.79,108,Dr. Reed

b

In [7]:
students.loc[:, "full_name"] = students["first_name"] + " " + students["last_name"]
students["full_name"]

0       Avery Nguyen
1         Maya Patel
2        Noah Garcia
3      Sofia Johnson
4          Ethan Kim
5      Liam Martinez
6       Olivia Brown
7       Lucas Wilson
8          Emma Chen
9        Mateo Davis
10    Isabella Lopez
11      Elijah Clark
12      Amara Taylor
13    Henry Anderson
14        Mia Thomas
15         Leo Moore
16        Nora Lewis
17       Samuel Hall
18         Zoe Allen
19      Daniel Young
20        Layla King
21     Julian Wright
22       Grace Scott
23        Owen Green
24       Chloe Baker
25       Isaac Adams
26      Elena Nelson
27        Caleb Hill
28     Aria Campbell
29    Miles Mitchell
Name: full_name, dtype: str

In [8]:
gpa_map = {row.student_id: row.gpa for row in students.itertuples()}
gpa_map

{'S1001': 3.51,
 'S1002': 2.71,
 'S1003': 2.81,
 'S1004': 3.05,
 'S1005': nan,
 'S1006': 3.52,
 'S1007': 3.75,
 'S1008': 2.89,
 'S1009': 3.07,
 'S1010': 2.59,
 'S1011': 3.22,
 'S1012': 3.31,
 'S1013': 2.77,
 'S1014': 2.66,
 'S1015': 3.81,
 'S1016': 3.31,
 'S1017': 2.88,
 'S1018': 3.95,
 'S1019': 3.3,
 'S1020': 3.75,
 'S1021': 3.83,
 'S1022': nan,
 'S1023': 2.49,
 'S1024': 3.73,
 'S1025': 3.85,
 'S1026': 3.29,
 'S1027': 3.45,
 'S1028': 3.79,
 'S1029': 2.58,
 'S1030': nan}

I filtered the students table to keep only those with a GPA above 3.0 and more than 45 completed credits because this gives a focused group of strong, advanced students. I created a new variable called full_name by combining first and last names to make the data easier to read. I used .loc[] to correctly assign this new column to the dataset. I also built a dictionary called gpa_map using a dictionary comprehension, which creates a quick lookup from each student’s ID to their GPA. This shows how Python can easily pull useful information out of the data.

Part 3 — Joining Tables

In [32]:
# Merge enrollments ↔ students

# Expected relationship: Each student can appear in many enrollments, but each enrollment belongs to exactly one student. This is a one‑to‑many relationship on student_id.
# Merge 1: students ↔ enrollments (OUTER)
merge1 = students.merge(
    enrollments,
    how="outer",
    on="student_id",
    validate="one_to_many",
)


merge1

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor,full_name,enrollment_id,course_id,term,status,midterm_score,final_score,project_score,attendance_pct
0,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72.0,Dr. Moreno,Avery Nguyen,E5001,C102,Spring 2026,Completed,96.0,65.0,65.0,94.7
1,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72.0,Dr. Moreno,Avery Nguyen,E5002,C106,Spring 2026,Completed,81.0,80.0,63.0,96.6
2,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72.0,Dr. Moreno,Avery Nguyen,E5003,C103,Spring 2026,Completed,77.0,67.0,72.0,88.6
3,S1002,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108.0,Dr. Shah,Maya Patel,E5004,C106,Fall 2025,Completed,86.0,NaN,85.0,77.3
4,S1002,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108.0,Dr. Shah,Maya Patel,E5005,C101,Fall 2025,Completed,90.0,55.0,79.0,85.8
5,S1003,Noah,Garcia,Mathematics,1st,18.0,Yes,Spring 2024,2.81,18.0,Dr. Reed,Noah Garcia,E5006,C102,Fall 2026,Enrolled,93.0,76.0,95.0,88.4
6,S1004,Sofia,Johnson,Computer Science,2nd,20.0,Yes,Spring 2026,3.05,63.0,Dr. Kim,Sofia Johnson,E5007,C105,Spring 2026,Completed,98.0,73.0,88.0,89.5
7,S1004,Sofia,Johnson,Computer Science,2nd,20.0,Yes,Spring 2026,3.05,63.0,Dr. Kim,Sofia Johnson,E5008,C101,Fall 2025,Completed,87.0,58.0,NaN,75.6
8,S1004,Sofia,Johnson,Computer Science,2nd,20.0,Yes,Spring 2026,3.05,63.0,Dr. Kim,Sofia Johnson,E5009,C104,Fall 2026,Enrolled,93.0,79.0,73.0,92.3
9,S1005,Ethan,Kim,Computer Science,4th,19.0,Yes,Spring 2025,NaN,18.0,Dr. Kim,Ethan Kim,E5010,C101,Spring 2026,Completed,73.0,57.0,99.0,82.9
10,S1005,Ethan,Kim,Computer Science,4th,19.0,Yes,Spring 2025,NaN,18.0,Dr. Kim,Ethan Kim,E5011,C108,Fall 2025,Completed,68.0,55.0,82.0,91.0
11,S1006,Liam,Martinez,Statistics,3rd,27.0,Yes,Spring 2024,3.52,45.0,Dr. Moreno,Liam Martinez,E5012,C105,Fall 2026,Enrolled,75.0,NaN,68.0,97.2
12,S1006,Liam,Martinez,Statistics,3rd,27.0,Yes,Spring 2024,3.52,45.0,Dr. Moreno,Liam Martinez,E5013,C101,Fall 2026,Enrolled,98.0,81.0,82.0,80.0
13,S1007,Olivia,Brown,Statistics,2nd,22.0,No,Spring 2026,3.75,36.0,Dr. Kim,Olivia Brown,E5014,C103,Fall 2025,Completed,61.0,93.0,86.0,85.8
14,S1007,Olivia,Brown,Statistics,2nd,22.0,No,Spring 2026,3.75,36.0,Dr. Kim,Olivia Brown,E5015,C106,Spring 2026,Completed,59.0,82.0,60.0,96.9
15,S1008,Lucas,Wilson,Data Science,4th,27.0,Yes,Spring 2024,2.89,45.0,Dr. Shah,Lucas Wilson,E5016,C104,Spring 2026,Completed,83.0,83.0,78.0,85.8
16,S1008,Lucas,Wilson,Data Science,4th,27.0,Yes,Spring 2024,2.89,45.0,Dr. Shah,Lucas Wilson,E5017,C102,Fall 2025,Completed,89.0,65.0,79.0,NaN
17,S1008,Lucas,Wilson,Data Science,4th,27.0,Yes,Spring 2024,2.89,45.0,Dr. Shah,Lucas Wilson,E5018,C101,Spring 2026,Completed,74.0,70.0,62.0,87.4
18,S1008,Lucas,Wilson,Data Science,4th,27.0,Yes,Spring 2024,2.89,45.0,Dr. Shah,Lucas Wilson,E5059,C999,Fall 2026,Enrolled,79.0,82.0,86.0,89.0
19,S1009,Emma,Chen,Data Science,3rd,27.0,Yes,Fall 2024,3.07,45.0,Dr. Moreno,Emma Chen,E5019,C103,Fall 2026,Enrolled,84.0,61.0,81.0,74.4
20,S1009,Emma,Chen,Data Science,3rd,27.0,Yes,Fall 2024,3.07,45.0,Dr. Moreno,Emma Chen,E5020,C108,Spring 2026,Completed,73.0,NaN,71.0,84.2
21,S1010,Mateo,Davis,Data Science,4th,27.0,Yes,Fall 2023,2.59,24.0,Dr. Reed,Mateo Davis,E5021,C102,Fall 2026,Enrolled,74.0,97.0,81.0,79.5
22,S1010,Mateo,Davis,Data Science,4th,27.0,Yes,Fall 2023,2.59,24.0,Dr. Reed,Mateo Davis,E5022,C108,Fall 2026,Enrolled,66.0,70.0,100.0,72.1
23,S1011,Isabella,Lopez,Statistics,2nd,18.0,Yes,Fall 2024,3.22,54.0,Dr. Reed,Isabella Lopez,E5023,C108,Fall 2026,Enrolled,61.0,59.0,79.0,94.4
24,S1012,Elijah,Clark,Data Science,4th,26.0,Yes,Fall 2025,3.31,72.0,Dr. Reed,Elijah Clark,E5024,C108,Fall 2026,Enrolled,66.0,76.0,66.0,78.0
25,S1013,Amara,Taylor,Data Science,4th,NaN,Yes,Spring 2024,2.77,108.0,Dr. Kim,Amara Taylor,E5025,C108,Fall 2025,Completed,83.0,70.0,NaN,91.2
26,S1013,Amara,Taylor,Data Science,4th,NaN,Yes,Spring 2024,2.77,108.0,Dr. Kim,Amara Taylor,E5026,C104,Fall 2026,Enrolled,68.0,78.0,77.0,81.7
27,S1014,Henry,Anderson,Mathematics,1st,20.0,Yes,Spring 2025,2.66,45.0,Dr. Shah,Henry Anderson,E5027,C102,Fall 2025,Completed,71.0,62.0,61.0,82.3
28,S1014,Henry,Anderson,Mathematics,1st,20.0,Yes,Spring 2025,2.66,45.0,Dr. Shah,Henry Anderson,E5028,C101,Fall 2025,Completed,88.0,NaN,77.0,77.6
29,S1015,Mia,Thomas,Statistics,3rd,23.0,Yes,Fall 2024,3.81,36.0,Dr. Shah,Mia Thomas,E5029,C105,Fall 2026,Enrolled,61.0,96.0,88.0,82.3
30,S1016,Leo,Moore,Data Science,2nd,25.0,Yes,Spring 2026,3.31,96.0,Dr. Moreno,Leo Moore,E5030,C106,Fall 2026,Enrolled,79.0,98.0,96.0,79.1
31,S1016,Leo,Moore,Data Science,2nd,25.0,Yes,Spring 2026,3.31,96.0,Dr. Moreno,Leo Moore,E5031,C101,Fall 2025,Completed,76.0,64.0,99.0,89.7
32,S1016,Leo,Moore,Data Science,2nd,25.0,Yes,Spring 2026,3.31,96.0,Dr. Moreno,Leo Moore,E5032,C102,Spring 2026,Completed,75.0,89.0,75.0,74.4
33,S1017,Nora,Lewis,Mathematics,2nd,19.0,Yes,Spring 2025,2.88,96.0,Dr. Moreno,Nora Lewis,E5033,C102,Fall 2025,Completed,70.0,97.0,87.0,96.9
34,S1017,Nora,Lewis,Mathematics,2nd,19.0,Yes,Spring 2025,2.88,96.0,Dr. Moreno,Nora Lewis,E5034,C107,Spring 2026,Completed,61.0,70.0,86.0,NaN
35,S1018,Samuel,Hall,Computer Science,4th,27.0,Yes,Fall 2025,3.95,36.0,Dr. Kim,Samuel Hall,E5035,C108,Fall 2026,Enrolled,74.0,87.0,64.0,99.8
36,S1018,Samuel,Hall,Computer Science,4th,27.0,Yes,Fall 2025,3.95,36.0,Dr. Kim,Samuel Hall,E5036,C107,Fall 2026,Enrolled,61.0,64.0,93.0,73.7
37,S1018,Samuel,Hall,Computer Science,4th,27.0,Yes,Fall 2025,3.95,36.0,Dr. Kim,Samuel Hall,E5037,C105,Spring 2026,Completed,58.0,NaN,65.0,95.9
38,S1019,Zoe,Allen,Statistics,4th,18.0,No,Spring 2025,3.30,18.0,Dr. Shah,Zoe Allen,E5038,C104,Fall 2025,Completed,77.0,62.0,97.0,74.1
39,S1019,Zoe,Allen,Statistics,4th,18.0,No,Spring 2025,3.30,18.0,Dr. Shah,Zoe Allen,E5039,C103,Fall 2026,Enrolled,61.0,77.0,95.0,96.1
40,S1020,Daniel,Young,Mathematics,1st,22.0,Yes,Fall 2023,3.75,108.0,Dr. Shah,Daniel Young,E5040,C103,Fall 2025,Completed,91.0,61.0,73.0,97.6
41,S1020,Daniel,Young,Mathematics,1st,22.0,Yes,Fall 2023,3.75,108.0,Dr. Shah,Daniel Young,E5041,C102,Spring 2026,Completed,67.0,56.0,76.0,80.4
42,S1021,Layla,King,Computer Science,2nd,22.0,Yes,Spring 2025,3.83,30.0,Dr. Shah,Layla King,E5042,C107,Fall 2025,Completed,89.0,68.0,NaN,73.9
43,S1021,Layla,King,Computer Science,2nd,22.0,Yes,Spring 2025,3.83,30.0,Dr. Shah,Layla King,E5043,C101,Fall 2026,Enrolled,79.0,92.0,71.0,91.9
44,S1022,Julian,Wright,Statistics,3rd,19.0,Yes,Spring 2025,NaN,18.0,Dr. Shah,Julian Wright,E5044,C107,Fall 2025,Completed,76.0,74.0,72.0,92.6
45,S1022,Julian,Wright,Statistics,3rd,19.0,Yes,Spring 2025,NaN,18.0,Dr. Shah,Julian Wright,E5045,C102,Spring 2026,Completed,62.0,61.0,71.0,85.2
46,S1023,Grace,Scott,Data Science,1st,19.0,Yes,Fall 2023,2.49,45.0,Dr. Moreno,Grace Scott,E5046,C102,Fall 2025,Completed,98.0,84.0,86.0,80.6
47,S1023,Grace,Scott,Data Science,1st,19.0,Yes,Fall 2023,2.49,45.0,Dr. Moreno,Grace Scott,E5047,C106,Spring 2026,Completed,70.0,74.0,98.0,77.8
48,S1024,Owen,Green,Data Science,2nd,26.0,Yes,Spring 2026,3.73,45.0,Dr. Kim,Owen Green,E5048,C106,Fall 2026,Enrolled,77.0,85.0,66.0,73.0
49,S1024,Owen,Green,Data Science,2nd,26.0,Yes,Spring 2026,3.73,45.0,Dr. Kim,Owen Green,E5049,C101,Spring 2026,Completed,77.0,84.0,82.0,83.5
50,S1025,Chloe,Baker,Data Science,4th,19.0,Yes,Spring 2024,3.85,84.0,Dr. Moreno,Chloe Baker,E5050,C102,Fall 2025,Completed,80.0,79.0,64.0,79.7
51,S1025,Chloe,Baker,Data Science,4th,19.0,Yes,Spring 2024,3.85,84.0,Dr. Moreno,Chloe Baker,E5051,C106,Fall 2025,Completed,92.0,58.0,75.0,87.6
52,S1026,Isaac,Adams,Statistics,4th,23.0,Yes,Fall 2024,3.29,36.0,NaN,Isaac Adams,E5052,C104,Fall 2026,Enrolled,70.0,63.0,68.0,90.7
53,S1027,Elena,Nelson,Computer Science,2nd,27.0,Yes,Fall 2024,3.45,36.0,Dr. Kim,Elena Nelson,E5053,C107,Fall 2026,Enrolled,87.0,64.0,94.0,77.3
54,S1028,Caleb,Hill,Mathematics,1st,20.0,No,Spring 2026,3.79,108.0,Dr. Reed,Caleb Hill,E5054,C107,Fall 2025,Completed,85.0,98.0,88.0,72.1
55,S1028,Caleb,Hill,Mathematics,1st,20.0,No,Spring 2026,3.79,108.0,Dr. Reed,Caleb Hill,E5055,C105,Spring 2026,Completed,73.0,95.0,85.0,91.9
56,S1029,Aria,Campbell,Data Science,2nd,NaN,Yes,Spring 2025,2.58,54.0,Dr. Moreno,Aria Campbell,E5056,C104,Spring 2026,Completed,88.0,57.0,85.0,80.3
57,S1029,Aria,Campbell,Data Science,2nd,NaN,Yes,Spring 2025,2.58,54.0,Dr. Moreno,Aria Campbell,E5057,C108,Fall 2026,Enrolled,73.0,62.0,78.0,94.2
58,S1030,Miles,Mitchell,Computer Science,4th,22.0,Yes,Fall 2024,NaN,36.0,Dr. Kim,Miles Mitchell,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,S9999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E5058,C106,Fall 2026,Enrolled,84.0,88.0,91.0,94.0

In [39]:
# Merge with courses (many-to-one)

# Expected relationship: Each course can appear in many enrollments, but each enrollment refers to exactly one course. This is a many‑to‑one relationship on course_id.
final = merge1.merge(
    courses,
    how="left",                
    on="course_id",
    validate="many_to_one",
    indicator=True
)

final

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,...,final_score,project_score,attendance_pct,department,course_number,course_title,credits,level,delivery,_merge
0,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72.0,...,65.0,65.0,94.7,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid,both
1,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72.0,...,80.0,63.0,96.6,STA,556.0,Statistics and Data Science Computing Workflows,3.0,Graduate,In Person,both
2,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72.0,...,67.0,72.0,88.6,CS,126.0,Introduction to Computing,4.0,Undergraduate,In Person,both
3,S1002,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108.0,...,NaN,85.0,77.3,STA,556.0,Statistics and Data Science Computing Workflows,3.0,Graduate,In Person,both
4,S1002,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108.0,...,55.0,79.0,85.8,STA,141.0,Exploratory Data Analysis,3.0,Undergraduate,In Person,both
5,S1003,Noah,Garcia,Mathematics,1st,18.0,Yes,Spring 2024,2.81,18.0,...,76.0,95.0,88.4,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid,both
6,S1004,Sofia,Johnson,Computer Science,2nd,20.0,Yes,Spring 2026,3.05,63.0,...,73.0,88.0,89.5,STA,444.0,Statistical Computing,3.0,Undergraduate,Online,both
7,S1004,Sofia,Johnson,Computer Science,2nd,20.0,Yes,Spring 2026,3.05,63.0,...,58.0,NaN,75.6,STA,141.0,Exploratory Data Analysis,3.0,Undergraduate,In Person,both
8,S1004,Sofia,Johnson,Computer Science,2nd,20.0,Yes,Spring 2026,3.05,63.0,...,79.0,73.0,92.3,MAT,239.0,Linear Algebra,3.0,Undergraduate,In Person,both
9,S1005,Ethan,Kim,Computer Science,4th,19.0,Yes,Spring 2025,NaN,18.0,...,57.0,99.0,82.9,STA,141.0,Exploratory Data Analysis,3.0,Undergraduate,In Person,both
10,S1005,Ethan,Kim,Computer Science,4th,19.0,Yes,Spring 2025,NaN,18.0,...,55.0,82.0,91.0,MAT,442.0,Probability,3.0,Undergraduate,Hybrid,both
11,S1006,Liam,Martinez,Statistics,3rd,27.0,Yes,Spring 2024,3.52,45.0,...,NaN,68.0,97.2,STA,444.0,Statistical Computing,3.0,Undergraduate,Online,both
12,S1006,Liam,Martinez,Statistics,3rd,27.0,Yes,Spring 2024,3.52,45.0,...,81.0,82.0,80.0,STA,141.0,Exploratory Data Analysis,3.0,Undergraduate,In Person,both
13,S1007,Olivia,Brown,Statistics,2nd,22.0,No,Spring 2026,3.75,36.0,...,93.0,86.0,85.8,CS,126.0,Introduction to Computing,4.0,Undergraduate,In Person,both
14,S1007,Olivia,Brown,Statistics,2nd,22.0,No,Spring 2026,3.75,36.0,...,82.0,60.0,96.9,STA,556.0,Statistics and Data Science Computing Workflows,3.0,Graduate,In Person,both
15,S1008,Lucas,Wilson,Data Science,4th,27.0,Yes,Spring 2024,2.89,45.0,...,83.0,78.0,85.8,MAT,239.0,Linear Algebra,3.0,Undergraduate,In Person,both
16,S1008,Lucas,Wilson,Data Science,4th,27.0,Yes,Spring 2024,2.89,45.0,...,65.0,79.0,NaN,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid,both
17,S1008,Lucas,Wilson,Data Science,4th,27.0,Yes,Spring 2024,2.89,45.0,...,70.0,62.0,87.4,STA,141.0,Exploratory Data Analysis,3.0,Undergraduate,In Person,both
18,S1008,Lucas,Wilson,Data Science,4th,27.0,Yes,Spring 2024,2.89,45.0,...,82.0,86.0,89.0,NaN,NaN,NaN,NaN,NaN,NaN,left_only
19,S1009,Emma,Chen,Data Science,3rd,27.0,Yes,Fall 2024,3.07,45.0,...,61.0,81.0,74.4,CS,126.0,Introduction to Computing,4.0,Undergraduate,In Person,both
20,S1009,Emma,Chen,Data Science,3rd,27.0,Yes,Fall 2024,3.07,45.0,...,NaN,71.0,84.2,MAT,442.0,Probability,3.0,Undergraduate,Hybrid,both
21,S1010,Mateo,Davis,Data Science,4th,27.0,Yes,Fall 2023,2.59,24.0,...,97.0,81.0,79.5,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid,both
22,S1010,Mateo,Davis,Data Science,4th,27.0,Yes,Fall 2023,2.59,24.0,...,70.0,100.0,72.1,MAT,442.0,Probability,3.0,Undergraduate,Hybrid,both
23,S1011,Isabella,Lopez,Statistics,2nd,18.0,Yes,Fall 2024,3.22,54.0,...,59.0,79.0,94.4,MAT,442.0,Probability,3.0,Undergraduate,Hybrid,both
24,S1012,Elijah,Clark,Data Science,4th,26.0,Yes,Fall 2025,3.31,72.0,...,76.0,66.0,78.0,MAT,442.0,Probability,3.0,Undergraduate,Hybrid,both
25,S1013,Amara,Taylor,Data Science,4th,NaN,Yes,Spring 2024,2.77,108.0,...,70.0,NaN,91.2,MAT,442.0,Probability,3.0,Undergraduate,Hybrid,both
26,S1013,Amara,Taylor,Data Science,4th,NaN,Yes,Spring 2024,2.77,108.0,...,78.0,77.0,81.7,MAT,239.0,Linear Algebra,3.0,Undergraduate,In Person,both
27,S1014,Henry,Anderson,Mathematics,1st,20.0,Yes,Spring 2025,2.66,45.0,...,62.0,61.0,82.3,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid,both
28,S1014,Henry,Anderson,Mathematics,1st,20.0,Yes,Spring 2025,2.66,45.0,...,NaN,77.0,77.6,STA,141.0,Exploratory Data Analysis,3.0,Undergraduate,In Person,both
29,S1015,Mia,Thomas,Statistics,3rd,23.0,Yes,Fall 2024,3.81,36.0,...,96.0,88.0,82.3,STA,444.0,Statistical Computing,3.0,Undergraduate,Online,both
30,S1016,Leo,Moore,Data Science,2nd,25.0,Yes,Spring 2026,3.31,96.0,...,98.0,96.0,79.1,STA,556.0,Statistics and Data Science Computing Workflows,3.0,Graduate,In Person,both
31,S1016,Leo,Moore,Data Science,2nd,25.0,Yes,Spring 2026,3.31,96.0,...,64.0,99.0,89.7,STA,141.0,Exploratory Data Analysis,3.0,Undergraduate,In Person,both
32,S1016,Leo,Moore,Data Science,2nd,25.0,Yes,Spring 2026,3.31,96.0,...,89.0,75.0,74.4,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid,both
33,S1017,Nora,Lewis,Mathematics,2nd,19.0,Yes,Spring 2025,2.88,96.0,...,97.0,87.0,96.9,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid,both
34,S1017,Nora,Lewis,Mathematics,2nd,19.0,Yes,Spring 2025,2.88,96.0,...,70.0,86.0,NaN,CS,345.0,Databases,3.0,Undergraduate,Online,both
35,S1018,Samuel,Hall,Computer Science,4th,27.0,Yes,Fall 2025,3.95,36.0,...,87.0,64.0,99.8,MAT,442.0,Probability,3.0,Undergraduate,Hybrid,both
36,S1018,Samuel,Hall,Computer Science,4th,27.0,Yes,Fall 2025,3.95,36.0,...,64.0,93.0,73.7,CS,345.0,Databases,3.0,Undergraduate,Online,both
37,S1018,Samuel,Hall,Computer Science,4th,27.0,Yes,Fall 2025,3.95,36.0,...,NaN,65.0,95.9,STA,444.0,Statistical Computing,3.0,Undergraduate,Online,both
38,S1019,Zoe,Allen,Statistics,4th,18.0,No,Spring 2025,3.30,18.0,...,62.0,97.0,74.1,MAT,239.0,Linear Algebra,3.0,Undergraduate,In Person,both
39,S1019,Zoe,Allen,Statistics,4th,18.0,No,Spring 2025,3.30,18.0,...,77.0,95.0,96.1,CS,126.0,Introduction to Computing,4.0,Undergraduate,In Person,both
40,S1020,Daniel,Young,Mathematics,1st,22.0,Yes,Fall 2023,3.75,108.0,...,61.0,73.0,97.6,CS,126.0,Introduction to Computing,4.0,Undergraduate,In Person,both
41,S1020,Daniel,Young,Mathematics,1st,22.0,Yes,Fall 2023,3.75,108.0,...,56.0,76.0,80.4,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid,both
42,S1021,Layla,King,Computer Science,2nd,22.0,Yes,Spring 2025,3.83,30.0,...,68.0,NaN,73.9,CS,345.0,Databases,3.0,Undergraduate,Online,both
43,S1021,Layla,King,Computer Science,2nd,22.0,Yes,Spring 2025,3.83,30.0,...,92.0,71.0,91.9,STA,141.0,Exploratory Data Analysis,3.0,Undergraduate,In Person,both
44,S1022,Julian,Wright,Statistics,3rd,19.0,Yes,Spring 2025,NaN,18.0,...,74.0,72.0,92.6,CS,345.0,Databases,3.0,Undergraduate,Online,both
45,S1022,Julian,Wright,Statistics,3rd,19.0,Yes,Spring 2025,NaN,18.0,...,61.0,71.0,85.2,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid,both
46,S1023,Grace,Scott,Data Science,1st,19.0,Yes,Fall 2023,2.49,45.0,...,84.0,86.0,80.6,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid,both
47,S1023,Grace,Scott,Data Science,1st,19.0,Yes,Fall 2023,2.49,45.0,...,74.0,98.0,77.8,STA,556.0,Statistics and Data Science Computing Workflows,3.0,Graduate,In Person,both
48,S1024,Owen,Green,Data Science,2nd,26.0,Yes,Spring 2026,3.73,45.0,...,85.0,66.0,73.0,STA,556.0,Statistics and Data Science Computing Workflows,3.0,Graduate,In Person,both
49,S1024,Owen,Green,Data Science,2nd,26.0,Yes,Spring 2026,3.73,45.0,...,84.0,82.0,83.5,STA,141.0,Exploratory Data Analysis,3.0,Undergraduate,In Person,both
50,S1025,Chloe,Baker,Data Science,4th,19.0,Yes,Spring 2024,3.85,84.0,...,79.0,64.0,79.7,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid,both
51,S1025,Chloe,Baker,Data Science,4th,19.0,Yes,Spring 2024,3.85,84.0,...,58.0,75.0,87.6,STA,556.0,Statistics and Data Science Computing Workflows,3.0,Graduate,In Person,both
52,S1026,Isaac,Adams,Statistics,4th,23.0,Yes,Fall 2024,3.29,36.0,...,63.0,68.0,90.7,MAT,239.0,Linear Algebra,3.0,Undergraduate,In Person,both
53,S1027,Elena,Nelson,Computer Science,2nd,27.0,Yes,Fall 2024,3.45,36.0,...,64.0,94.0,77.3,CS,345.0,Databases,3.0,Undergraduate,Online,both
54,S1028,Caleb,Hill,Mathematics,1st,20.0,No,Spring 2026,3.79,108.0,...,98.0,88.0,72.1,CS,345.0,Databases,3.0,Undergraduate,Online,both
55,S1028,Caleb,Hill,Mathematics,1st,20.0,No,Spring 2026,3.79,108.0,...,95.0,85.0,91.9,STA,444.0,Statistical Computing,3.0,Undergraduate,Online,both
56,S1029,Aria,Campbell,Data Science,2nd,NaN,Yes,Spring 2025,2.58,54.0,...,57.0,85.0,80.3,MAT,239.0,Linear Algebra,3.0,Undergraduate,In Person,both
57,S1029,Aria,Campbell,Data Science,2nd,NaN,Yes,Spring 2025,2.58,54.0,...,62.0,78.0,94.2,MAT,442.0,Probability,3.0,Undergraduate,Hybrid,both
58,S1030,Miles,Mitchell,Computer Science,4th,22.0,Yes,Fall 2024,NaN,36.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
59,S9999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88.0,91.0,94.0,STA,556.0,Statistics and Data Science Computing Workflows,3.0,Graduate,In Person,both

In this dataset, duplicated rows occur because a single student can appear in multiple enrollment records. When the tables are combined, the student‑level information (such as student_id, first_name, program, advisor, etc.) must be repeated for each enrollment that belongs to that student. For example, S1001 appears in three different enrollment records (E5001, E5002, E5003). As a result, the student’s attributes are duplicated across three rows in the merged dataset. This duplication is expected and correct: each enrollment is a separate observation, and each observation must carry the student’s information.

Part 4 — Missing Data and Reshaping

In [44]:
# Missing counts
missing_counts = final.isna().sum()

# Missing percentages
missing_percent = final.isna().mean() * 100

missing_counts, missing_percent

(student_id           0
 first_name           1
 last_name            1
 program              1
 year                 1
 age                  5
 active               1
 entry_term           1
 gpa                  6
 credits_completed    1
 advisor              2
 full_name            1
 enrollment_id        1
 course_id            1
 term                 1
 status               1
 midterm_score        1
 final_score          6
 project_score        4
 attendance_pct       3
 department           2
 course_number        2
 course_title         2
 credits              2
 level                2
 delivery             2
 _merge               0
 dtype: int64,
 student_id            0.000000
 first_name            1.666667
 last_name             1.666667
 program               1.666667
 year                  1.666667
 age                   8.333333
 active                1.666667
 entry_term            1.666667
 gpa                  10.000000
 credits_completed     1.666667
 advisor               3.333333
 full_name             1.666667
 enrollment_id         1.666667
 course_id             1.666667
 term                  1.666667
 status                1.666667
 midterm_score         1.666667
 final_score          10.000000
 project_score         6.666667
 attendance_pct        5.000000
 department            3.333333
 course_number         3.333333
 course_title          3.333333
 credits               3.333333
 level                 3.333333
 delivery              3.333333
 _merge                0.000000
 dtype: float64)

In [48]:
missing_gpa = final.loc[final["gpa"].isna()]
missing_gpa

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,...,final_score,project_score,attendance_pct,department,course_number,course_title,credits,level,delivery,_merge
9,S1005,Ethan,Kim,Computer Science,4th,19.0,Yes,Spring 2025,NaN,18.0,...,57.0,99.0,82.9,STA,141.0,Exploratory Data Analysis,3.0,Undergraduate,In Person,both
10,S1005,Ethan,Kim,Computer Science,4th,19.0,Yes,Spring 2025,NaN,18.0,...,55.0,82.0,91.0,MAT,442.0,Probability,3.0,Undergraduate,Hybrid,both
44,S1022,Julian,Wright,Statistics,3rd,19.0,Yes,Spring 2025,NaN,18.0,...,74.0,72.0,92.6,CS,345.0,Databases,3.0,Undergraduate,Online,both
45,S1022,Julian,Wright,Statistics,3rd,19.0,Yes,Spring 2025,NaN,18.0,...,61.0,71.0,85.2,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid,both
58,S1030,Miles,Mitchell,Computer Science,4th,22.0,Yes,Fall 2024,NaN,36.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
59,S9999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88.0,91.0,94.0,STA,556.0,Statistics and Data Science Computing Workflows,3.0,Graduate,In Person,both

In [59]:
wide_scores = final[[
    "student_id",
    "enrollment_id",
    "course_id",
    "term",
    "midterm_score",
    "final_score",
    "project_score"
]]

wide_scores.head()

,student_id,enrollment_id,course_id,term,midterm_score,final_score,project_score
0,S1001,E5001,C102,Spring 2026,96.0,65.0,65.0
1,S1001,E5002,C106,Spring 2026,81.0,80.0,63.0
2,S1001,E5003,C103,Spring 2026,77.0,67.0,72.0
3,S1002,E5004,C106,Fall 2025,86.0,NaN,85.0
4,S1002,E5005,C101,Fall 2025,90.0,55.0,79.0

In [63]:
# Select the columns we want to reshape
score_cols = ["midterm_score", "final_score", "project_score"]
# Melt the dataset from wide → long
long_scores = final.melt(
    id_vars=["student_id", "enrollment_id", "course_id", "term"],
    value_vars=score_cols,
    var_name="assessment_type",
    value_name="score"
)

long_scores.head()

  student_id enrollment_id course_id         term assessment_type  score
0      S1001         E5001      C102  Spring 2026   midterm_score   96.0
1      S1001         E5002      C106  Spring 2026   midterm_score   81.0
2      S1001         E5003      C103  Spring 2026   midterm_score   77.0
3      S1002         E5004      C106    Fall 2025   midterm_score   86.0
4      S1002         E5005      C101    Fall 2025   midterm_score   90.0

Replacing missing values with zero is inappropriate because zero is a meaningful numeric value, not a neutral placeholder. Substituting zero changes the distribution of the variable, artificially lowers averages, and introduces bias into any statistical analysis. It also incorrectly implies that missing scores or missing GPA values represent actual zero performance, which is not true. Missing values should be handled using appropriate methods such as imputation or exclusion depending on the context.

Part 5 — Reproducible submission

In [65]:
final.to_csv("../data/processed/final_analysis.csv", index=False)