In [142]:
import pandas as pd

In [143]:
data = {
    "id": [101, 102, 103, 104, 105, 106],
    "age": [24, 31, 27, 19, 42, 35],
    "group": ["A", "B", "A", "B", "A", "B"],
    "score": [81, 94, 88, 72, 91, 85]
}

df = pd.DataFrame(data)

In [144]:
df

    id  age group  score
0  101   24     A     81
1  102   31     B     94
2  103   27     A     88
3  104   19     B     72
4  105   42     A     91
5  106   35     B     85

In [145]:
df.head()
df.shape
df.columns
df.index
df.dtypes
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      6 non-null      int64
 1   age     6 non-null      int64
 2   group   6 non-null      str
 3   score   6 non-null      int64
dtypes: int64(3), str(1)
memory usage: 324.0 bytes

               id        age      score
count    6.000000   6.000000   6.000000
mean   103.500000  29.666667  85.166667
std      1.870829   8.189424   7.884584
min    101.000000  19.000000  72.000000
25%    102.250000  24.750000  82.000000
50%    103.500000  29.000000  86.500000
75%    104.750000  34.000000  90.250000
max    106.000000  42.000000  94.000000

Questions
How many observations are there? 6

How many variables? 4

Which columns are numeric? id, age, score

What is the default index? 0

What does df.shape return? # of rows=6, # of columns=4

In [146]:
age = df["age"]
type(age)

pandas.Series

In [147]:
age_df = df[["age"]]
type(age_df)

pandas.DataFrame

df["age"] gives a 1D Series, while df[["age"]] gives a 2D DataFrame containing the same column.

In [148]:
df["score"]

0    81
1    94
2    88
3    72
4    91
5    85
Name: score, dtype: int64

In [149]:
df[["age", "score"]]

   age  score
0   24     81
1   31     94
2   27     88
3   19     72
4   42     91
5   35     85

In [150]:
analysis_df=df[["id","group", "score"]]

In [151]:
analysis_df

    id group  score
0  101     A     81
1  102     B     94
2  103     A     88
3  104     B     72
4  105     A     91
5  106     B     85

In [152]:
df.iloc[0]

id       101
age       24
group      A
score     81
Name: 0, dtype: object

In [153]:
df.iloc[0:3]

    id  age group  score
0  101   24     A     81
1  102   31     B     94
2  103   27     A     88

In [154]:
df.iloc[[0, 2, 5]]

    id  age group  score
0  101   24     A     81
2  103   27     A     88
5  106   35     B     85

In [155]:
df.iloc[1:4, 1:3]

   age group
1   31     B
2   27     A
3   19     B

Questions
What does the first argument to .iloc[] control? The first argument selects rows by position.

What does the second argument control? The second argument selects columns by position.

Is the stop value included in positional slicing? No — the stop value is NOT included.

In [156]:
df = df.set_index("id")

In [157]:
df
df.index

RangeIndex(start=101, stop=107, step=1, name='id')

In [158]:
df.loc[101]

age      24
group     A
score    81
Name: 101, dtype: object

In [159]:
df.iloc[0]

age      24
group     A
score    81
Name: 101, dtype: object

Reflection
1. df.loc[101]
This selects the row whose index label is 101.

Because you set "id" as the index, 101 is now a label, not a position.

So .loc means:

✔ “Find the row with index label 101.”
2. df.iloc[0]
This selects the first row by position, regardless of what the index label is.

So .iloc means:

✔ “Give me the row in position 0.”

In [160]:
df.loc[101]

age      24
group     A
score    81
Name: 101, dtype: object

In [161]:
df.loc[[101, 103, 105]]

     age group  score
id
101   24     A     81
103   27     A     88
105   42     A     91

In [162]:
df.loc[
    [101, 103],
    ["age", "score"]
]

     age  score
id
101   24     81
103   27     88

In [163]:
df.loc[
    [102, 104,106],
    ["age", "group", "score"]
]

     age group  score
id
102   31     B     94
104   19     B     72
106   35     B     85

In [164]:
small = pd.DataFrame(
    {"value": [10, 20, 30, 40]},
    index=[101, 205, 310, 412]
)

In [165]:
small.loc[205]

value    20
Name: 205, dtype: int64

In [166]:
small.iloc[1]

value    20
Name: 205, dtype: int64

.loc  uses: .loc uses index labels
.iloc uses: .iloc uses integer positions

In [167]:
df.iloc[1:4]

     age group  score
id
102   31     B     94
103   27     A     88
104   19     B     72

In [168]:
df.loc[102:105]

     age group  score
id
102   31     B     94
103   27     A     88
104   19     B     72
105   42     A     91

Question
Why does label‑based slicing behave differently from positional slicing?
✔ Because .loc slicing is inclusive, while .iloc slicing is exclusive.
.iloc[start:stop]  
→ uses positions  
→ behaves like normal Python slicing
→ stop is NOT included

.loc[start_label:stop_label]  
→ uses index labels  
→ includes both the start and stop labels  
→ stop IS included

In [169]:
df.loc[:, ["age", "score"]]

     age  score
id
101   24     81
102   31     94
103   27     88
104   19     72
105   42     91
106   35     85

In [170]:
df.loc[
    102:105,
    ["age", "score"]
]

     age  score
id
102   31     94
103   27     88
104   19     72
105   42     91

In [171]:
df.loc[
    101:104,
    ["group", "score"]
]

    group  score
id
101     A     81
102     B     94
103     A     88
104     B     72

In [172]:
condition = df["score"] > 80

In [173]:
condition
type(condition)

pandas.Series

In [174]:
df.loc[condition]

     age group  score
id
101   24     A     81
102   31     B     94
103   27     A     88
105   42     A     91
106   35     B     85

Question
What does each True and False represent?
✔ Each True or False represents whether the condition is satisfied for that row.
More specifically:

True → that row’s score is greater than 80

False → that row’s score is not greater than 80

In [175]:
df.loc[df["score"] > 80]

     age group  score
id
101   24     A     81
102   31     B     94
103   27     A     88
105   42     A     91
106   35     B     85

In [176]:
df.loc[df["age"] >= 30]

     age group  score
id
102   31     B     94
105   42     A     91
106   35     B     85

In [177]:
df.loc[df["group"] == "A"]

     age group  score
id
101   24     A     81
103   27     A     88
105   42     A     91

In [178]:
df.loc[df["age"] < 30]

     age group  score
id
101   24     A     81
103   27     A     88
104   19     B     72

In [179]:
df.loc[df["group"] == "B"]

     age group  score
id
102   31     B     94
104   19     B     72
106   35     B     85

In [180]:
df.loc[df["score"] >= 85]

     age group  score
id
102   31     B     94
103   27     A     88
105   42     A     91
106   35     B     85

In [181]:
df.loc[
    (df["age"] < 30) &
    (df["score"] > 80)
]

     age group  score
id
101   24     A     81
103   27     A     88

In [182]:
df.loc[
    (df["group"] == "A") |
    (df["score"] > 90)
]

     age group  score
id
101   24     A     81
102   31     B     94
103   27     A     88
105   42     A     91

In [183]:
df.loc[
    ~(df["group"] == "A")
]

     age group  score
id
102   31     B     94
104   19     B     72
106   35     B     85

In [184]:
df.loc[
    (df["age"] >= 30) &
    (df["score"] >= 85)
]

     age group  score
id
102   31     B     94
105   42     A     91
106   35     B     85

In [185]:
df.loc[
    (df["group"] == "A") &
    (df["score"] >= 90)
]

     age group  score
id
105   42     A     91

Question
Did your result match your prediction? Yes

In [186]:
df.loc[
    df["score"] >= 85,
    ["age", "group", "score"]
]

     age group  score
id
102   31     B     94
103   27     A     88
105   42     A     91
106   35     B     85

In [187]:
df.loc[
    df["age"] >= 30,
    ["group", "score"]
]

    group  score
id
102     B     94
105     A     91
106     B     85

In [188]:
df2 = pd.DataFrame(
    {
        "id": range(201, 209),
        "group": ["A", "B", "C", "A", "C", "B", "A", "C"],
        "score": [81, 94, 88, 72, 91, 85, 79, 96]
    }
).set_index("id")

In [189]:
df2.loc[
    df2["group"].isin(["A", "C"])
]

    group  score
id
201     A     81
203     C     88
204     A     72
205     C     91
207     A     79
208     C     96

In [190]:
df2.loc[
    df2["group"].isin(["B", "C"]) & (df2["score"] >= 85)
]

    group  score
id
202     B     94
203     C     88
205     C     91
206     B     85
208     C     96

In [191]:
missing_df = pd.DataFrame(
    {
        "id": [1, 2, 3, 4, 5],
        "age": [21, 32, None, 45, 28],
        "score": [81, None, 77, 92, 88]
    }
).set_index("id")

In [192]:
missing_df
missing_df.isna()
missing_df.isna().sum()

age      1
score    1
dtype: int64

In [193]:
missing_df.loc[
    missing_df["score"].isna()
]

     age  score
id
2   32.0    NaN

In [194]:
missing_df.loc[
    missing_df["score"].notna()
]

     age  score
id
1   21.0   81.0
3    NaN   77.0
4   45.0   92.0
5   28.0   88.0

Reflection
Why is score = 0 different from score = missing in statistical analysis?
Ans: It means the participant actually scored zero.
It means you do not know the score.

In [195]:
df["performance"] = "medium"

In [196]:
df.loc[
    df["score"] >= 90,
    "performance"
] = "high"

In [197]:
df.loc[
    df["score"] < 80,
    "performance"
] = "low"

In [198]:
df.loc[
    df["age"] < 30,
    "age_group"
] = "young"

In [199]:
df.loc[
    df["age"] >= 30,
    "age_group"
] = "older"

In [200]:
df[df["score"] > 80]["score"] = 100

/tmp/ipykernel_5783/2702008686.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[df["score"] > 80]["score"] = 100

In [201]:
# Age criterion: age >= 30
# Score criterion: score >= 85
# Missing-data criterion: score is not missing
# Variables required: age, group, score

In [202]:
analysis = df.loc[
    (df["age"] >= 30) &
    (df["score"] >= 85) &
    (df["score"].notna()),
    ["age", "group", "score"]
]

Age criterion:
Score criterion:
Missing-data criterion:
Variables required:

eligible = (
    (df["age"] >= 30) &
    (df["score"] >= 85) &
    (df["score"].notna())
)

analysis_df = df.loc[
    eligible,
    ["age", "group", "score"]
]